project_id = "rmdhmufsfnojavsybkvc"

[auth]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = false

[functions.assistant-chat]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = false
