name: hrm_pro_flutter
description: Human Resource Management Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  fl_chart: ^0.65.0
  table_calendar: ^3.0.9
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  uuid: ^4.2.1
  flutter_local_notifications: ^16.2.0
  url_launcher: ^6.2.1
  cached_network_image: ^3.3.0
  flutter_slidable: ^3.0.1
  flutter_markdown: ^0.6.18
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0
  dio: ^5.3.3
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^12.1.1
  flutter_animate: ^4.3.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  flutter_colorpicker: ^1.0.3
  syncfusion_flutter_calendar: ^23.2.7
  syncfusion_flutter_charts: ^23.2.7
  syncfusion_flutter_datagrid: ^23.2.7
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_screenutil: ^5.9.0
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700