// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmdhmufsfnojavsybkvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZGhtdWZzZm5vamF2c3lia3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxODMxNTUsImV4cCI6MjA5NDc1OTE1NX0.fGn8hzafCDHc4Ysxnj32jbJKDj0H49Bl0jDi41pADQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});